"""empty message

Revision ID: 007cb3be8ecd
Revises: 77d2fdce8855
Create Date: 2021-04-22 01:39:47.793613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007cb3be8ecd'
down_revision = '77d2fdce8855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tutores_birthday_key', 'tutores', type_='unique')
    op.drop_constraint('tutores_curriculum_key', 'tutores', type_='unique')
    op.drop_constraint('tutores_specialty_key', 'tutores', type_='unique')
    op.drop_constraint('tutores_tutor_name_key', 'tutores', type_='unique')
    op.drop_constraint('tutores_url_curriculum_key', 'tutores', type_='unique')
    op.drop_constraint('tutores_user_lastname_key', 'tutores', type_='unique')
    op.drop_constraint('tutorias_category_key', 'tutorias', type_='unique')
    op.drop_constraint('tutorias_cost_key', 'tutorias', type_='unique')
    op.drop_constraint('tutorias_info_detail_key', 'tutorias', type_='unique')
    op.drop_constraint('tutorias_info_specifies_key', 'tutorias', type_='unique')
    op.drop_constraint('tutorias_rating_key', 'tutorias', type_='unique')
    op.drop_constraint('tutorias_specialty_key', 'tutorias', type_='unique')
    op.drop_constraint('tutorias_tutorships_name_key', 'tutorias', type_='unique')
    op.drop_constraint('user_birthday_key', 'user', type_='unique')
    op.drop_constraint('user_user_lastname_key', 'user', type_='unique')
    op.drop_constraint('user_user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_user_name_key', 'user', ['user_name'])
    op.create_unique_constraint('user_user_lastname_key', 'user', ['user_lastname'])
    op.create_unique_constraint('user_birthday_key', 'user', ['birthday'])
    op.create_unique_constraint('tutorias_tutorships_name_key', 'tutorias', ['tutorships_name'])
    op.create_unique_constraint('tutorias_specialty_key', 'tutorias', ['specialty'])
    op.create_unique_constraint('tutorias_rating_key', 'tutorias', ['rating'])
    op.create_unique_constraint('tutorias_info_specifies_key', 'tutorias', ['info_specifies'])
    op.create_unique_constraint('tutorias_info_detail_key', 'tutorias', ['info_detail'])
    op.create_unique_constraint('tutorias_cost_key', 'tutorias', ['cost'])
    op.create_unique_constraint('tutorias_category_key', 'tutorias', ['category'])
    op.create_unique_constraint('tutores_user_lastname_key', 'tutores', ['user_lastname'])
    op.create_unique_constraint('tutores_url_curriculum_key', 'tutores', ['url_curriculum'])
    op.create_unique_constraint('tutores_tutor_name_key', 'tutores', ['tutor_name'])
    op.create_unique_constraint('tutores_specialty_key', 'tutores', ['specialty'])
    op.create_unique_constraint('tutores_curriculum_key', 'tutores', ['curriculum'])
    op.create_unique_constraint('tutores_birthday_key', 'tutores', ['birthday'])
    # ### end Alembic commands ###
