"""empty message

Revision ID: 719e2d077bd6
Revises: 7e18628039ba
Create Date: 2021-04-27 02:42:08.096117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719e2d077bd6'
down_revision = '7e18628039ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutoria_contratada',
    sa.Column('id_tc', sa.Integer(), nullable=False),
    sa.Column('tutoria_id_fk', sa.Integer(), nullable=True),
    sa.Column('user_id_fk', sa.Integer(), nullable=True),
    sa.Column('fecha_contrato', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fecha_cierre', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['tutoria_id_fk'], ['tutorias.id_tt'], ),
    sa.ForeignKeyConstraint(['user_id_fk'], ['user.id_u'], ),
    sa.PrimaryKeyConstraint('id_tc')
    )
    op.drop_table('tutoriacontratada')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutoriacontratada',
    sa.Column('id_tc', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tutoria_id_fk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id_fk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_contrato', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fecha_cierre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tutoria_id_fk'], ['tutorias.id_tt'], name='tutoriacontratada_tutoria_id_fk_fkey'),
    sa.ForeignKeyConstraint(['user_id_fk'], ['user.id_u'], name='tutoriacontratada_user_id_fk_fkey'),
    sa.PrimaryKeyConstraint('id_tc', name='tutoriacontratada_pkey')
    )
    op.drop_table('tutoria_contratada')
    # ### end Alembic commands ###
