"""empty message

Revision ID: 83b78df58081
Revises: 
Create Date: 2021-04-24 00:46:27.147787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b78df58081'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutores',
    sa.Column('id_t', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('tutor_id', sa.String(length=120), nullable=False),
    sa.Column('tutor_name', sa.String(length=120), nullable=False),
    sa.Column('tutor_lastname', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('curriculum', sa.String(length=120), nullable=False),
    sa.Column('url_curriculum', sa.String(length=120), nullable=False),
    sa.Column('birthday', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('direction', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id_t'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tutor_id')
    )
    op.create_table('user',
    sa.Column('id_u', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('user_lastname', sa.String(length=120), nullable=False),
    sa.Column('birthday', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('direction', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id_u'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tutorias',
    sa.Column('id_tt', sa.Integer(), nullable=False),
    sa.Column('tutorships_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('info_specifies', sa.String(length=120), nullable=False),
    sa.Column('info_detail', sa.String(length=120), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('tutor_id_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id_fk'], ['tutores.id_t'], ),
    sa.PrimaryKeyConstraint('id_tt')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutorias')
    op.drop_table('user')
    op.drop_table('tutores')
    # ### end Alembic commands ###
