"""empty message

Revision ID: 852efe475a2e
Revises: 83b78df58081
Create Date: 2021-04-24 02:45:13.329143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852efe475a2e'
down_revision = '83b78df58081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutoriacontratada',
    sa.Column('id_tc', sa.Integer(), nullable=False),
    sa.Column('tutoria_id_fk', sa.Integer(), nullable=True),
    sa.Column('user_id_fk', sa.Integer(), nullable=True),
    sa.Column('fecha_contrato', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fecha_cierre', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['tutoria_id_fk'], ['tutorias.id_tt'], ),
    sa.ForeignKeyConstraint(['user_id_fk'], ['user.id_u'], ),
    sa.PrimaryKeyConstraint('id_tc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutoriacontratada')
    # ### end Alembic commands ###
